// Generated by CoffeeScript 2.5.1
(function() {
  var BrowserWindow, app, mainWindow, ready, session, tests;

  ({app, BrowserWindow, session} = require('electron'));

  mainWindow = null;

  tests = [/pagead/, /get_midroll_info/, /moatads/, /pubads/, /amazon-adsystem/, /video_ads/];

  ready = function() {
    session.defaultSession.webRequest.onBeforeSendHeaders(function(details, cb) {
      details.requestHeaders['User-Agent'] = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0';
      return cb({
        requestHeaders: details.requestHeaders
      });
    });
    session.defaultSession.webRequest.onBeforeRequest(function(details, cb) {
      var i, len, result, test;
      result = false;
      for (i = 0, len = tests.length; i < len; i++) {
        test = tests[i];
        if (test.test(details.url)) {
          result = true;
          break;
        }
      }
      return cb({
        cancel: result
      });
    });
    mainWindow = new BrowserWindow({
      width: 800,
      height: 600,
      alwaysOnTop: true
    });
    return mainWindow.loadURL('https://www.youtube.com/feed/subscriptions', {
      userAgent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0'
    });
  };

  app.on('ready', ready);

  app.on('window-all-closed', function() {
    return process.platform === 'darwin' || app.quit();
  });

  app.on('activate', function() {
    return mainWindow || ready();
  });

}).call(this);
